language: python
python:
  - 3.6
before_install:
  - if [ "$encrypted_debe730ce1aa_key" != "" ]; then openssl aes-256-cbc -K $encrypted_debe730ce1aa_key -iv $encrypted_debe730ce1aa_iv -in `pwd`/deploy-mojp-dbs-pipelines.id_rsa.enc -out `pwd`/deploy-mojp-dbs-pipelines.id_rsa -d; fi
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.3.2.deb && sudo service elasticsearch restart
install:
  - make install
script:
  - make test
cache:
  directories:
  - "$HOME/.cache"
addons:
  apt:
    packages:
      - oracle-java8-set-default
deploy:
  provider: script
  script: if [ "$encrypted_debe730ce1aa_key" != "" ]; then ssh -i `pwd`/deploy-mojp-dbs-pipelines.id_rsa bhs@devapi.dbs.bh.org.il; fi
  on:
    branch: master
