language: python
python:
  - 3.6
install:
  - cp .travis/docker-compose.override.yml docker-compose.override.yml
  - bin/docker/build_tests.sh
script:
  - bin/docker/run_tests
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
sudo: required
services:
  - docker
