language: python
python:
  - 3.6
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.3.2.deb && sudo service elasticsearch restart
install:
  - make install
script:
  - make test
  - make docker-build
cache:
  directories:
    - $HOME/.cache
addons:
  apt:
    packages:
      - oracle-java8-set-default
services:
  - docker
